### ISSUE TITLE
queue and Qr Code for every new player

### ISSUE THREAD

**Issue by misterrioes** [flo-bit/youtube-party-dj#19]
Currently there is only one queue for everyone that visits the site.
There should be a seperate queue and a linked QR Code for every player-instance.
If someone opens the QR Code he is redirected to the Client-UI that displays only the queue from that player.

**Comment by thaleius** [comment]
will be solved in #23 and #28

**Comment by thaleius** [comment]
> Currently there is only one queue for everyone that visits the site. There should be a seperate queue and a linked QR Code for every player-instance. If someone opens the QR Code he is redirected to the Client-UI that displays only the queue from that player.

will be solved in #23 and #28
