### ISSUE TITLE
Stop videos to be added to queue multiple times.

### ISSUE THREAD

**Issue by misterrioes** [flo-bit/youtube-party-dj#31]
Currently you can add the same song multiple times to the queue which results in unwanted behaviour. Meaning when you vote for one song the votes count for both. 

![Image](https://github.com/flo-bit/youtube-party-dj/assets/55053428/01849a28-f919-4b31-a478-c276b3ec2cb6)

**Comment by flo-bit** [comment]
duplicate of #26, closing this
